### ISSUE TITLE
Container default errors

### ISSUE THREAD

**Issue by metanomy** [axiom-data-science/docker-thredds#1]
I tried running the container without specifying any options other than ports, and received a bunch of errors related to config files not being found. Details at this gist: https://gist.github.com/metanomy/8caa3c89eb20ff3f80e0

**Comment by kwilcox** [comment]
@metanomy this is fixed, please try running the latest release on Docker Hub

**Comment by rsignell-usgs** [comment]
@metanomy , have you tried this again?
