### ISSUE TITLE
Beautiful!

### ISSUE THREAD

**Issue by lesserwhirls** [axiom-data-science/docker-thredds#3]
Thanks to @rsignell-usgs for point this out! We used docker in our summer training workshop last summer, but have not kept up on the docker images. That said, have done an awesome job with this @kwilcox! @rsignell-usgs says they use your docker build for their stuff, and I can see why - as the title says, it's beautiful (simple, clean, includes ncSoS, etc.).

What can we do to help out on this effort?

**Comment by kwilcox** [comment]
Thanks @lesserwhirls!

Please submit pull requests as you releases new versions.. that would be a huge help!  Tracking `thredds_config.xml` configuration changes between TDS versions (additional cache configuration, different defaults, etc.) is really the hardest part (not hard at all... it's been fairly stable). 

I've been doing a branch for each major version (`4.6`, `5.0`, `5.x`, etc.) and keeping `master` at whatever the `stable` release is. Each branch builds automatically into a different image.

**Comment by lesserwhirls** [comment]
We can do that for sure. We just released 4.6.5, and I just made a PR. I noticed you create a tdm user, but it does not look like the TDM is getting installed. Have you given thought to if/how you would like to do that? We have a docker container that includes the TDM, so we could help add that functionality if you are interested.

**Comment by kwilcox** [comment]
Good call.  I don't deal in GRIB files so have not needed the TDM at all. I was envisioning a separate docker container for the TDM.

**Comment by julienchastang** [comment]
Great news that several of us are Dockerizing the TDS/TDM. These three effort (one internal to the TDS project, two [Unidata-Dockerfiles](https://github.com/Unidata/Unidata-Dockerfiles/tree/master/tds-base) , three this one) all have there particular advantages. May I suggest we unify our efforts under one project? I propose a Unidata/docker-thredds project that will combine these three projects.

**Comment by lesserwhirls** [comment]
Ah, the things in Unidata Dockerfiles totally slipped my mind. I was only
considering the one internal to the TDS.

**Comment by kwilcox** [comment]
@julienchastang sounds great, shall I transfer this repository to the Unidata organization? Would you be willing to give me push privileges for the repository?

**Comment by rsignell-usgs** [comment]
@lesserwhirls , are you the gatekeeper here?

**Comment by kwilcox** [comment]
pokey poke poke poke

**Comment by lesserwhirls** [comment]
Sorry I let this slip. I am actually not the gatekeeper for the Unidata repos, but @ddirks or @oxelson may be able to help with the repo transfer.

I don't have an issue with you (@kwilcox) having push privileges. Our workflow has been to do things on a branch and make pull requests (even internally). This is great for the TDS, where we have turned off direct pushes to master and have tests that must pass before PRs can be merged with master (thanks to TravisCI). Not currently the case with this, as there is no testing, but if we had tests, I'd suggest a similar workflow (maybe down the road?)

**Comment by julienchastang** [comment]
I too have left this slip. Sorry. I am actually making slow progress towards getting back to this issue and this is high priority for me to work with you and my Unidata cohorts. Just to reinforce what Sean said, the Unidata github repo is locked down, even for Unidata staff. Would it be possible to simply proceed with good old git/github branches and forks? Of course, we are eager to give credit where credit is due. This week is booked and I am on vacation in the beginning of July but maybe we can shoot for end of August for completing this objective?

Briefly, I hope to unify our effort with a top-level Unidata github repo that would encompass a Docker project for running the TDS/TDM in a manner that everyone is happy with. I have completed this goal for other projects (e.g., RAMADDA, LDM). I just have not gotten back to the TDS/TDM yet. At this point, Unidata really needs to have a solid Docker image for the TDS/TDM.

**Comment by lesserwhirls** [comment]
I'm not sure what would happen, but if you try to transfer the repository to Unidata, will it let you? It's possible we (Unidata) might need to fork the repo before transferring.

**Comment by rsignell-usgs** [comment]
If you make kyle an admin he can transfer, then you can remove him.  You don't need to fork.

**Comment by julienchastang** [comment]
If the repo lives under the Unidata account, can it be named thredds-docker, pretty please :-) so that it is consistent with ldm-docker and ramadda-docker. Thanks!

**Comment by lesserwhirls** [comment]
Would it be possible to transfer it to @oxelson? She could get it into Unidata pretty easily at that point.

**Comment by kwilcox** [comment]
I'll transfer it to @oxelson if she can get it into the Unidata organization. Someone at Unidata will need to setup the automated builds on hub.docker.com as well. Right now there are builds setup for each branch (correspond to major TDS versions). We could also use tags to build each specific version.

We should also get TDM support into this before advertising.

**Comment by lesserwhirls** [comment]
Sounds good @kwilcox - @julienchastang has the TDM support in our Docker container, so I don't think it will be a huge deal to merge our efforts together. I do not have experience getting hub.docker.com to do automated builds, but last I looked it did not look too crazy.

**Comment by julienchastang** [comment]
I concur with @lesserwhirls that I can merge my stuff (the TDM etc.) at a later point. Normally, I would also like help out the dockerhub stuff, but I am leaving on vacation imminently and going dark for a while (until 7/11). There's a lot of docker expertise in Unidata at this point. Maybe ping Ward for assistance? Also again, if possible, it would nice to have the repo named thredds-docker for a consistent Docker portfolio at github.com/Unidata.

**Comment by kwilcox** [comment]
Ethan just brought up on the TST call that we should also be including the HDF5 libraries in the container.

**Comment by julienchastang** [comment]
Hi. Unless there are any objections, I am going to create a top-level thredds-docker (naming it consistently with our other Docker projects) repository at Unidata (in process). I will then push axiom-data-science/docker-thredds project to that repository. I will also push the relevant images to dockerhub (more or less mirroring what is here: https://hub.docker.com/r/axiom/docker-thredds/). I will subsequently fold in docker-compose and TDM improvements. On the axiom end, I propose forking that newly created Unidata repo and proceeding via github issues/pull requests. Sound OK?

**Comment by kwilcox** [comment]
@julienchastang Sounds good. Is the `compose` stuff to run the `tdm` beside `tds`? Will it be a separate image with its own repository?

**Comment by julienchastang** [comment]
docker-compose should work for both the TDS and TDM (as it did before w/ our previous attempt). I am planning on keeping the TDM Docker related files in the same repo but have separate images. At least that is the plan at this point. This is going to take a few days to implement and test out.

**Comment by julienchastang** [comment]
The initial port seems to have gone smoothly:
- https://hub.docker.com/r/unidata/thredds-docker/
- https://github.com/Unidata/thredds-docker

Let us know if you see problems. 

At this point, you can fork thredds-docker and proceed via github issues and pull requests. (The work flow we have adopted here at Unidata is create a github issue and send PRs that reference and close that issue.) 

On my end, I'll fold in the docker-compose and TDM stuff in the coming days.
