### ISSUE TITLE
Upgrade 5.0 to latest artifact

### ISSUE THREAD

**Issue by rsignell-usgs** [axiom-data-science/docker-thredds#7]
As mentioned here:
https://github.com/Unidata/thredds/issues/526#issuecomment-231472064
there is a new TDS 5.0 artifact:
http://artifacts.unidata.ucar.edu/content/repositories/unidata-snapshots/edu/ucar/tds/5.0.0-SNAPSHOT/tds-5.0.0-20160708.184540-12.war
can we rebuild the Docker container please?   :pray:

**Comment by kwilcox** [comment]
Would you mind sending a PR to the `5.0` branch with the news SNAPSNOT version?  See https://github.com/axiom-data-science/docker-thredds/commit/c73888a11b0d4bd422d058d4925199b41bec9683 for an example

**Comment by rsignell-usgs** [comment]
Okay, I can do this later today

**Comment by kwilcox** [comment]
Fixed in https://github.com/axiom-data-science/docker-thredds/pull/8
